<?php
/**
 * @package Hankeme_Cookiepolicy
 * @authors Jan Strohmeier [jan.strohmeier@hanke.me]
 * @developers Jan Strohmeier [jan.strohmeier@hanke.me]
 * @web http://www.hankeme.de
 * @version 0.1.0
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0) 
 */
?>
<?php if($layer = $this->getLayer()) : ?>

	<?php if($layer['type'] == 'opt_in') : ?>

		<script type="text/javascript">
			document.observe("dom:loaded", function() {
				var text = '<?php echo $this->__($layer["message"], $layer["link"]); ?>';
				Dialog.alert(
					text, 
					{
						className: "cookielayer", 
						width:540, 
						okLabel: "<?php echo $this->__($layer['ok_button']);?>",
						ok: function(win) {
							document.cookie = "hankeme_cookiepolicy=1"; return true;
						}
					}
				);
			});
		</script>

	<?php elseif($layer['type'] == 'opt_out') : ?>

		<div class="hankeme_cookiepolicy_optout_info" id="hankeme_cookiepolicy_optout_info" style="display:block; position:fixed; bottom:0; text-align:center; padding: 10px; width:100%; border-top:1px solid #cccccc; background: #eeeeee;">
			<p>
				<?php echo $this->__($layer["message"], $layer["link"]); ?>
			</p>
			<a class="button" onclick="document.cookie='hankeme_cookiepolicy=1'; $('hankeme_cookiepolicy_optout_info').hide();" href="javascript:void(0)">
				<span><span><?php echo $this->__($layer['ok_button']);?></span></span>
			</a>
		</div>

	<?php elseif($layer['type'] == 'hint_once') : ?>

		<div class="hankeme_cookiepolicy_optout_info" id="hankeme_cookiepolicy_optout_info" style="display:block; position:fixed; bottom:0; text-align:center; padding: 10px; width:100%; border-top:1px solid #cccccc; background: #eeeeee;">
			<p>
				<?php echo $this->__($layer["message"], $layer["link"]); ?>
			</p>
		</div>

	<?php endif; ?>
<?php endif; ?>
